### ISSUE TITLE
More information about a request "listingFavorites"

### ISSUE THREAD

**Issue by JorisBodin** [nextcloud/ios#1026]
Hi,

In the file "CCFavorites" at 178, the method "listingFavorites" call 2 times a route.
`https://server.com/remote.php/dav/files/1337`
It's call in "REPORT", why ?
This route it's not call in Android App.
We already know if a file is in favorites when we update the list of files.

So I don't really understand this method.

Thanks you :)

**Comment by marinofaggiana** [comment]
Hi @JorisBodin this view is very very old and will require a new review in swift with the  UICollectionView and with the use of new driver https://github.com/nextcloud/ios-communication-library.
 
1 - REPORT because I need a list of Favorite in all directories (not only the update files) 

2 - @tobiasKaminsky what do you use for listing Favorites in Android ?

**Comment by JorisBodin** [comment]
If I read correctly the code, in Android is "SEARCH" method :)

**Comment by marinofaggiana** [comment]
I don't know if is better ( more performance ) the "SEARCH" or "REPORT" method in webDAV

**Comment by tobiasKaminsky** [comment]
In my tests report is way faster than search, but for Android it lacks the mime type:
https://github.com/nextcloud/android-library/pull/273
