### ISSUE TITLE
Microsoft Word for iOS can't save to Nextcloud

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#1049]
From MS Word save a blank document on Nextcloud via File Provider extension return error.

**Comment by marinofaggiana** [comment]
Please test with 2.25.3 build 4 in TestFlight

**Comment by nikslor** [comment]
Will test as soon as 2.25.3 (4) is available in testflight - right now 2.25.3 (3) is the most recent one.

**Comment by nikslor** [comment]
I briefly testes 2.25.3 (4) and could not reproduce the issue anymore.

From what I can tell, the issue is fixed, but we'll do more testing and let you know if we run into more problems.

Thanks a lot to the whole Nextcloud team and especially Marino for delivering this fix in such a short amount of time - very much appreciated!
