### ISSUE TITLE
Push notifications are still received

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#1312]
- have an "old" client installed 
- add two accounts
- test push on both accounts
- remove one account
- send push to this deleted account
- see notification, but "no decrypt" or just a plain "Notification" shown

Expected behaviour:
- Show only notification if notification is still valid on server and content can be retrieved
- do not show "empty" notifications
- remove push token on app removal / account removal

When I completely remove the app and try it again, I could not reproduce it.

**Comment by MorrisJobke** [comment]
I experience the same. cc @marinofaggiana

**Comment by marinofaggiana** [comment]
@Ivansss do you have a little time ? :-)

**Comment by Ivansss** [comment]
I could take a look at it @marinofaggiana ;)

**Comment by MorrisJobke** [comment]
@Ivansss @MorrisJobke I still run into this

**Comment by Ivansss** [comment]
Sorry for my late reply here.

The app should unregister the user from the push proxy and from nextcloud notifications when removing the account.
If this process fails for some reason, the app will still receive push notifications that the app can't hide neither decrypt. 

I think the only solution for this problem then it's to remove the "old app token" (the one the app was using for that user) from Settings -> Security using the web interface.
This will make the push proxy realize that it should not send more pushes to this app token.
Re-installing the app will make the trick too, since the push token of the app will be different. But that's a worse solution in my opinion.

**Comment by MorrisJobke** [comment]
> If this process fails for some reason, the app will still receive push notifications that the app can't hide neither decrypt.

So all notifications need to be shown? There is no way to just hide them? Because that would be one way to avoid this.

But let me check if I can trigger this error again.

**Comment by Ivansss** [comment]
> So all notifications need to be shown? There is no way to just hide them? Because that would be one way to avoid this.

We can't hide them no :( We were able to hide them before when we were using VoIP pushes, but that's not possible any more.

**Comment by MorrisJobke** [comment]
Resolved now 👍
