### ISSUE TITLE
File App - Importing to NextCloud.

### ISSUE THREAD

**Issue by sakthi-d** [nextcloud/ios#1500]
Hello Team,

Importing a file to next cloud via Files App is not available? if available, please provide us the way to do it or steps.
I might be wrong or missed something. Thanks in advance.

**Comment by marinofaggiana** [comment]
Hi, please ?

**Comment by sakthi-d** [comment]
Hello @marinofaggiana ,

Uploading/Importing files to owncloud via iOS Native Files App. That is FileProviderExtension. OwnCloud is not listed after choosing an image from the gallery and "Save to Files".

**Comment by sakthi-d** [comment]
If this is helpful,

![IMG_2079](https://user-images.githubusercontent.com/9445601/101148921-39c7bf00-3644-11eb-8a8a-1f0ada605fd5.PNG)

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/1448

**Comment by sakthi-d** [comment]
Yes, I've modified and added own-cloud in Files app. Files are viewed in Files App. This happens only on uploding/importing.
@marinofaggiana

**Comment by marinofaggiana** [comment]
Hi @sakthi-d  I don't understand can you write correctly:

### Expected behaviour                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             

### Actual behaviour                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               

### Steps to reproduce

**Comment by sakthi-d** [comment]
#### Expected Behaviour 
The selected image from the photos app should get uploaded in Own-cloud(via Files App).

 #### Actual behaviour 
Now, Owncloud is not selectable in the list.(i.e it's grayed out). Other apps like Dropbox, Google Drive can be selected from the list. 
P.S :   Files are getting previewed via Files App. Problem occurs when we try to upload a photo from Photos App.

#### Steps to reproduce
1. Select a photo in photos app
2. Tap a share icon
3. Save to Files 
4. Check the list

**Comment by marinofaggiana** [comment]
I don't understand why you write about : "Owncloud"

**Comment by johkoenig** [comment]
Hi @sakthi-d,
this is the issue tracker for the Nextcloud iOS app. The owncloud iOS app is developed here: https://github.com/owncloud/ios-app
I propose you report your problem there.
