### ISSUE TITLE
Auto Upload doesn't work iOS 

### ISSUE THREAD

**Issue by islamadel** [nextcloud/ios#1617]
### Steps to reproduce

1. Enable Auto Upload in NC App
2. Take Photos
3. Open NC App
4. No uploads!

### Expected behaviour

Should start uploading

### Actual behaviour

Nothing

### Screenshots

If applicable, add a screenshot showing the issue.

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Environment data

iOS 14.4.1

**Nextcloud iOS app version:** see More > Settings

3.4.2.0

**Server operating system:**

20.0.8

**Web server:** Apache, nginx

apache

**Database:**

**PHP version:**

**Nextcloud version:** see Nextcloud admin page

**Comment by marinofaggiana** [comment]
hi @islamadel what's do you mean for: No uploads!

**Comment by shofutex** [comment]
I have experienced the same issue.  NextCloud stopped seeing new photos on my device and I have to manually upload.

**Comment by mabe-pm** [comment]
Same issue here. Resetting the App didn't work.

**Comment by cieska** [comment]
Same here. My miss' iPhone stoped uploading long time ago. I remember some times ago it was required to keep the app open. But eventually I stoped keep trying as app itsel just freezing I do t know any other that on decent iPhone would be paging so much. Unacceptable. 

By the way this function to upload in background impossible to swtho on. Even when allowing GPS. I understand it as it's incomplete or maybe I have no clue how avarage user can make it work.

**Comment by dukey** [comment]
I have found that always allowing GPS access and enabling background
app refresh to work.

I've installed the Nextcloud app on a fresh phone, and while I haven't
done it in a V4.x version, I know by default, the required options were
not enabled.  Maybe this check should be run at every update of the app
to make  sure the user has them enabled if required.  People turn stuff
off and forget they did all the time..

**Comment by stoamandl** [comment]
The same behavior also for me with 4.04.0 NC 21.0.3 and IOS 14.6.
Only when opening the app, the images are synchronized. This does not happen in the background.
Even the activation of the background update does not change anything.

**Comment by marinofaggiana** [comment]
BACKGROUND: works when move the iPhone for "considerable" displacements (works with 3G/4G when change cell) and the battery il High or connected to te power.

WHY: iOS limit.

**Comment by stoamandl** [comment]
> BACKGROUND: works when move the iPhone for "considerable" displacements (works with 3G/4G when change cell) and the battery il High or connected to the power.
> 
> WHY: iOS limit.

If I understood your short explanation correctly, the automatic upload should work when I'm on wifi and my phone is connected to the charging cable?
This also does not help in any way.
No matter how and when I take pictures, they are only uploaded when I open the NC app.
Is this a limitation of iOS, or a bug of the app?

**Comment by cieska** [comment]
From my experience, I have spotted the trend that most of iPhone users are non technical savvy. They just expect that iPhone just works and it does it well they need to click one button.  And if something doesn't work then they even don't know that there is even a thing out there  :)) This is maybe why here isn't much of feedback here? And if let's ay it's tru that it's needs some iPhone settings to be adjusted then maybe would be a good thing for Devs to implement some sort of app self check function that it will detect that some iPhone OS settings must be activated to NX app to work properly then it can spit call out message or maybe it appears as system message to inform the user about the actions needed and how it's done.? 
Otherwise  I also still waiting for the proper solutions or bug fix. 
Thank you.

**Comment by shofutex** [comment]
I believe my issue was due to the age of my iPhone.  After upgrading to a new iPhone, the auto uploads are noticed, but it takes a minute or two for uploads to start.
