### ISSUE TITLE
Research: check available markdown libraries

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#1851]
- check for available markdown libraries
- must work locally
- support edit/save
- must support same markdown set as web

**Comment by thisIsTheFoxe** [comment]
### Apple APIs
- iOS 15+ [`NSAttributedString(markdown:)`](https://developer.apple.com/documentation/foundation/nsattributedstring/3796597-init)
- Support for earlier versions: [christianselig/Markdownosaur](https://github.com/christianselig/Markdownosaur)
  - uses [apple/swift-markdown](http://github.com/apple/swift-markdown)
    - uses GitHub-flavored Markdown
- (-) no quick-action buttons
- (-) no _live_ text formatting

I think this is the easiest solution. Similar to what GitHub does: Have a plain text editor for editing the raw markdown and the ability to preview the markdown separately.
I didn't really find anything that's similar to the NC web UI. Also, most of these use the SwiftUI framework which is often buggy when used with UIKit (as the Nextcloud iOS app does).

### [kyle-n/HighlightedTextEditor](https://github.com/kyle-n/HighlightedTextEditor)
- (+) actual *editor*
- (-) uses custom Regex instead of a parser
- (-) no quick-action buttons
- built with SwiftUI

### [johnxnguyen/Down](https://github.com/johnxnguyen/Down)
- Built on CommonMark
- (-) not an editor

### [qeude/SwiftDown](https://github.com/qeude/SwiftDown)
- (+) actual *editor*
- (+) customisable theming using `.json` file
- (-) no quick-action buttons
- built with SwiftUI & johnxnguyen/Down (CommonMark)
