### ISSUE TITLE
Option to disable "Keep app running" notification.

### ISSUE THREAD

**Issue by Subnet-Masked** [nextcloud/ios#2291]
### Steps to reproduce

1. Open Nextcloud
2. Close the app
3. Remove app from recents.

### Expected behaviour

App closes silently.

### Actual behaviour

An annoying notification appears telling the user to "Keep the app running for a better user experience"

### Screenshots

![22-12-16 18-12-16 2105](https://user-images.githubusercontent.com/55600371/208203726-8d95836c-0f94-4035-b503-336ffe49aabb.png)

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Reasoning or why should it be changed/implemented?

This notification appears every time you close the app causing mild annoyance for something I don't really care about. Would be nice to have an option to acknowledge the notification and have it not show again.

### Environment data

**iOS version:** e.g. iOS 16.1.1

**Nextcloud iOS app version:** 4.5.7.0

**Server operating system:** Docker / Unknown. Kubernetes.

**Web server:** Docker / Unknown. Through NGINX Ingress

**Database:** MariaDB

**PHP version:** Docker / Unknown.

**Nextcloud version:** 25.0.1

**Comment by marinofaggiana** [comment]
It's important maintain the app open in background

**Comment by Subnet-Masked** [comment]
@marinofaggiana May I ask why it is important? In usage I see no benefit or difference between closing it or keeping it open.

**Comment by darix** [comment]
1. your message should explain _why_ it is important ( I assume it is for the automatic photo sync )
2. Give us an option to turn off that notification. Not everyone is actually interested in the reasons why you prefer the app to stay open. some of us will actually open the sync for when we feel it is the right time. 

Right now the behavior is super annoying and patronizing.

**Comment by marinofaggiana** [comment]
- Detect Photo 
- Upload works in background, every process in background will be terminate.

and, I don't understand why terminate apps ?!

**Comment by darix** [comment]
1. save battery
2. save bandwidth
3. only using the nextcloud client to occasionally download files and not actually using any of those uploading/syncing features.

just to name a few.

**Comment by marinofaggiana** [comment]
Argh so much misinformation.

**Comment by darix** [comment]
Maybe it is just a lack of you explaining why we now get annoyed by notifications when we actually do not care about nextcloud running in the background because no feature, that needs the client running in the background, is interesting for us.

A simple toggle in the settings "Warn when stopping nextcloud app" and the people who dont care about the feature can get rid of the notification spam.

**Comment by Subnet-Masked** [comment]
Some of us seriously don't care about the features of the app that require background and some of us really hate keeping apps open in recents and wasting battery by leaving something in the background that we don't need.

I use photo sync, yes. But I don't want it running in the background. I get home, open the app and let it sync if I even took any pictures that day. Other than that the only thing I do is access files once in a while.

I never used to get this notification until a little while back and all was fine. Not to mention the notification at first inspection seems to suggest that I should keep the app in the foreground.

**Comment by marinofaggiana** [comment]
Keeping apps open does not mean memory/bandwidth or space usage. (In the background apps are literally frozen by mapping memory), in fact it consumes more battery power to keep restarting them.

Ending apps is an unnecessary bad habit.

As you can see, the notification instead serves precisely those of you who have this bad habit but then complain that the app is not working properly.

Note: If you want us to have no background process calls (detect new photo) uncheck "Background App Refresh" in the iOS settings of the app.

https://discussions.apple.com/docs/DOC-13491

This is a good text for understanding, otherwise on the Apple development site you will find clearly more technical explanations.

**Comment by darix** [comment]
you can still give us an option to turn off that notification. i will keep cleaning up apps that i no longer need to make switching between apps more efficient.

**Comment by Subnet-Masked** [comment]
@darix It looks like if you disable background app refresh, the notification stops appearing. Thanks @marinofaggiana for telling us about that setting.

(I miss my Android)

**Comment by tobx** [comment]
@marinofaggiana

> Ending apps is an unnecessary bad habit.

Unnecessary maybe, but not especially bad. At least the opinion of an iPhone developer:

https://www.inc.com/joel-comm/force-closing-apps-on-your-iphone-might-make-it-ru.html

And do you think it is a good habit for every app to use resources to remind users of bad habits or is Nextcloud special in any way here?

I think it is the best way to switch very fast between a few apps when all others are closed. Or do you know a faster way?

> but then complain that the app is not working properly.

I really do not expect the app to do anything when I close it, so I would never complain about something not working after I closed the app.

Also a good app is programmed in a way to expect to be closed at any time (battery low, phone turned off, user closes it for whatever reason).

**Comment by Rc-Cookie** [comment]
@marinofaggiana For me the obvious alternative to disabling the specific notification inside the app is to just disable notifications for the app all together. Would just be unfortunate if the app later had a notification actually worth seing.

**Comment by JericoPablo** [comment]
yeah i would like this too, dont really care about bad habits tbh.

**Comment by JericoPablo** [comment]
I really don't get why this is still solved yet. It's a simple function u need to enable. A toggle where the user decide if he wants it or not. Trying to force ur opinion to others is big no.

**Comment by jptlabs** [comment]
3 years old and there's still no option to disable it.

**Comment by zachariazh** [comment]
@marinofaggiana 99,9 % of people that get annoyed by that stupid notification will not come across your preaching here on Github. So whether your point of not closing apps is correct or not does not really matter, as people will continue to do so anyways.

They will either keep being annoyed by that notification, or turn off notifications for the app altogether, since iOS doesn't allow granularity in notification settings either.

Then i guess there are those like me, that **do** read this, and still have to turn off notifications for the app completely. So is it good UX design to have people not have notifications at all?

**Comment by shadowlocked** [comment]
As a new NextCloud user, just bumping this. Really crazy that we have to turn off all notifications to get rid of this message.

**Comment by tdyr** [comment]
I deinstalled the app. Was about thinking to get into nextcloud again. @marinofaggiana can you answer why you guys are so stubborn to not provide an option which would not affect anyone? You can enable it by default and everyone is happy. Is this some kind of power game you playing? 😂

**Comment by olejohanovreas** [comment]
Can this feature be added?
