### ISSUE TITLE
Login screen bug

### ISSUE THREAD

**Issue by mind22** [nextcloud/ios#234]
iPhone 6s/Nextcloud 2.17.2

Every time the app gets opened, after about 1-2 seconds the login screen appears. If you press cancel in the right top corner, you can use the app as usual.

P.S. I removed the account and added it again, didn't change anything. Also uninstall and new install of the app didn't help.

**Comment by rakekniven** [comment]
See my previous post at #233 
Regards.

**Comment by ho1ger** [comment]
I think I might have a similar problem here. However, I use Touch ID to unlock the app.

- when I open the Nextcloud App, the Touch ID dialogue is not triggered in some cases. Instead, I directly reach the files view.
- after some seconds, sometimes 2, sometimes more, the Fingerprint dialogue opens and I can authenticate myself.
- When I exit the App by pressing the Home button, the fingerprint dialogue appears again. I even noticed that this dialogue was shown minutes after using the Nextcloud App.

 I currently use 2.17.3.00007 on a 7 plus. I have seen that behavior since the second last update.

**Comment by marinofaggiana** [comment]
No change in version 2.1x on passcode view.... 🤔

**Comment by ho1ger** [comment]
Odd. These are the best bugs...

However I can report: Since yesterdays update to *.00008 it seems to be working again. Maybe this was just a glitch on my device. No idea.

**Comment by marinofaggiana** [comment]
Ok, thanks @ho1ger, I close this, if re-bug re-open 😄
