### ISSUE TITLE
iOS can't connect to server

### ISSUE THREAD

**Issue by james-at-purism** [nextcloud/ios#252]
First install.  In the server address field, I put in the local IP address for my Nextcloud server and I immediately get "connection error could not connect to the server."

**Comment by rakekniven** [comment]
Is your webinterface working?
Have you tried desktop app? 
Any other webdav app?

Please contact nextcloud forums for such questions. See https://help.nextcloud.com/

**Comment by james-at-purism** [comment]
Yes
Yes, working on windows, linux and mac
Not sure what you mean exactly.

**Comment by mario** [comment]
@rakekniven why close the issue right away? It was me who directed him to file an issue as this could potentially be a bug.

Please re-open the bug.

**Comment by rakekniven** [comment]
Hello @mario and @james-at-purism 
For such topics we normally discuss them on our forums. If it is a bug you can file an issue here.

To help the user we need way more information.
Which server OS? which nextcloud version?

There are different ways using different protocols to access your cloud.
The desktop client is using webdav.
Please see https://docs.nextcloud.com/server/12/user_manual/files/access_webdav.html and try.

Closed this isses because I am pretty sure this is not iOS app related.

**Comment by rakekniven** [comment]
> put in the local IP address for my Nextcloud server and I immediately get "connection error could not connect to the server."

You have to enter protocol in front of ip e.g. http://<your ip>
