### ISSUE TITLE
Include web login for IOS App

### ISSUE THREAD

**Issue by mdfarhanin** [nextcloud/ios#2726]
Cloud flare allows an extra layer of security for accessing the website by sending email opt to user before accessing site as per screenshot below 
![image](https://github.com/nextcloud/ios/assets/15947334/4bfe9726-86a3-4e41-a9f7-c01bafd6454f)

Reference: https://developers.cloudflare.com/cloudflare-one/api-terraform/access-api-examples/email/

The web browser allows to continue the login whereas the native mobile iOS app has disabled web login which defeats the extra layer of protection

screenshot from IOS app
![image](https://github.com/nextcloud/ios/assets/15947334/ef4b62cc-75b9-428f-926c-4fc16a2bdbc3)

Allow the iOS app to use web login to enable this security feature

**Comment by mritzmann** [comment]
> Allow the iOS app to use web login to enable this security feature

As far as I can tell, the iOS app already uses a login process/flow via web browser. You can test this by deactivating "Cloudflare Zero Trust". The problem is of a fundamental nature: With this Cloudflare feature, you also prevent Nextcloud from accessing other Nextcloud APIs/Endpoints. This is not only a problem when logging in, but also later when using it.

**Comment by joshtrichards** [comment]
Closing since this is out-of-scope.
