### ISSUE TITLE
Reveal Contacts and Events from Unified Search

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/ios#2845]
Relevant frameworks:

* [Contacts](https://developer.apple.com/documentation/contacts) for accessing the contacts.
* [EventKit](https://developer.apple.com/documentation/eventkit) for accessing the calendars.

Notes:
- How to reveal a contact: https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/AddressBook/Tasks/URLScheme.html
- How to reveal a calendar: https://stackoverflow.com/questions/29684423/open-calendar-from-swift-app

**Comment by i2h3** [comment]
## Deprecation Notice

The AddressBook framework is deprecated since iOS 9 (2015) and replaced with the Contacts framework. Unfortunately, the contacts framework does not offer to reveal a specific contact programmatically based on my current research (please correct me if I am wrong!). The contacts app can be opened only in general.

## Reliability

The discussed logic of revealing contacts and events in the iOS Contacts and Calendar apps is prone to failure in multiple ways:

1. Access to those data sources might be denied by the user.
2. It is impossible to know whether synchronization of those data sources with a Nextcloud server is set up. The chance of the local items not being existent is to be expected.
3. In example contacts ([`CNContact`](https://developer.apple.com/documentation/contacts/cncontact)) do not have globally unique identifiers. It is necessary to compare properties and make assumptions based on probability of the contact entries describing the same contact. There is no fail-safe way to ensure equality, though. It is only a "you probably mean this one because it looks similar". 

### Ambiguity Example

A remotely found contact might have the same first and last name and mail address like a locally found contact. However, the remotely found contact might not have any more information while the local one may be manually groomed by the user without synchronization to any server. If the user then changes the device and attempts to navigate to the same contact on the other device without it being found locally, it may be perceived as data loss. Also I assume it would be confusing to understand that actually the locally available contact is _not_ what has been found by the search on the server but only something like a duplicate.

## Conclusion

In regard to the issues above I would suggest to stick with the discussed fallback solution of revealing the result in the web user interface of the server as the only path. That is the only reliable way that the returned preview in the search result actually leads to the true source data and not some partially overlapping duplicate from another data source. Given the potential points of failures and unsafe assumptions it appears to offer a more reliable user experience.

**Comment by i2h3** [comment]
The server only provides a `displayName` for the result item regardless whether more detailed name information is filled in on the server. Those display name are arbitrary strings likely composed of multiple name parts. Examples:

* "Jane"
* "Jane Doe"
* "Jane van Doe"

This alone would require the implementation of parsing of this display name to separate its parts for use in a query of the normalized contacts database which uses atomic values like [`givenName`](https://developer.apple.com/documentation/contacts/cncontact/givenname) and [`familyName`](https://developer.apple.com/documentation/contacts/cncontact/familyname). Obviously, that approach is rather hopeless. 🤔

There is no display name to query against. The system derives one automatically based on locale (some locales write family names first instead of given names) and user preference (who can choose to override the writing order regardless of locale) unless the rather rarely used nickname field is used which is considered as a manual override by iOS.

**Comment by i2h3** [comment]
The problem for calendar events is similar but less severe. The search providers does not return normalized data but localized strings for presentation. So, changing from German language and locale on the server account results in the result data (`subline` property in particular) to change from `06.11.2024` to `Nov 6, 2024`. While dates like that can be parsed more reliably than display names, it may fail, too.

<details><summary>Example JSON Response</summary>

`GET https://redacted/ocs/v2.php/search/providers/calendar/search?term=Example%20Event`

```json
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": "OK"
    },
    "data": {
      "name": "Events",
      "isPaginated": true,
      "entries": [
        {
          "thumbnailUrl": "",
          "title": "Example Event 1",
          "subline": "Nov 6, 2024",
          "resourceUrl": "https://redacted",
          "icon": "icon-calendar-dark",
          "rounded": false,
          "attributes": {
            "createdAt": "1730851200"
          }
        }
      ],
      "cursor": 3
    }
  }
}
```
</details>
