### ISSUE TITLE
Uploaded Videos get downscaled

### ISSUE THREAD

**Issue by Jogaxell** [nextcloud/ios#3191]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

### Steps to reproduce
1. Upload a 4k video from your photo library to your Nextcloud via the mobile app.
2. Download the just uploaded video.
3. Check video size.

### Expected behaviour
Tell us what should happen

The video should not be downscaled/compressed.

### Actual behaviour
Tell us what happens instead, if possible also add a screenshot

The video is now compressed to 1080p.
Original video:
![Image](https://github.com/user-attachments/assets/261303dc-3a96-49c1-a865-3e1b3ed72e76)
Video downloaded from Nextcloud:
![Image](https://github.com/user-attachments/assets/7c9fc2ef-b21e-4fdb-a153-034bbb6ca555)

I think the problem lies partly on apples side. With iCloud Photos turned on I think Nextcloud only uploads the locally stored thumbnails/downscaled videos rather than the originals stored in iCloud. The Nextcloud app should therefore be first downloading the original from iCloud to the the device, then uploading them to your Nextcloud 

### Logs

```
If applicable, you can post the iOS app or server logs (removing any sensitive information).
```

### Reasoning or why should it be changed?
To not lose quality of uploaded files.

### Environment data

**iOS version:** iPadOS 18.0.1
Also tested on iOS 17.0

**Nextcloud iOS app version:** 5.5.5.0

**Server operating system:** Linux 6.6.32-production+truenas x86_64 

**Web server:** Apache, nginx

**Database:** PostgreSQL 13.1 (Debian 13.1-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

**PHP version:** 8.2.23

**Nextcloud version:** 29.0.5

**Comment by Torqu3Wr3nch** [comment]
Possibly also related to issue #2164 which highlights a more generalized issue whereby the format of the files downloaded locally to the iPhone are not preserved.

Did you check to see how the files were stored on your Nextcloud server itself? Are they stored there in the original 4k format or are they also showing 1080p?

**Comment by Jogaxell** [comment]
Sadly, it's stored in 1080p rather than 4k on the server itself. So the quality is permanently lost.
![Image](https://github.com/user-attachments/assets/e823640a-f1c2-44b7-b26a-164a1c1b8b8d)

**Comment by Torqu3Wr3nch** [comment]
@marinofaggiana, this wouldn't have affected autouploads, correct? Only manually uploaded videos?

Thank you in advance.

**Comment by Jogaxell** [comment]
@Torqu3Wr3nch I only discovered this issue through the autouploads.
 So yes, they are also affected.

**Comment by Torqu3Wr3nch** [comment]
Thank you for the reply.

Here is what's weird though: I checked my videos and my 4k video is showing as 4k. Additionally, when I download the video and examine it, I see that it is in fact stored as HEVC/H.265. Looking at @marinofaggiana's change, that should not be the case since AVAssetExportPresetHighestQuality compresses the video to H.264.

@Jogaxell, were your videos stored locally on your phone or were they only available on iCloud?

As far as I know, this command could just be called on download and so the files stored on your Nextcloud server itself are fine. Would you mind downloading the files on your desktop from the Nextcloud server itself and verifying if those files are correct in terms of resolution and codec (you can use VLC Media Player to check)?

I'm trying to gauge how disastrous this issue is in terms of data loss...

Thanks again!

**Comment by Jogaxell** [comment]
The affected videos were only available on iCloud, not stored locally on the device.

Locally stored video are not affected for me.

As I sat earlier, the affected videos are stored in lower quality on the server itself. The screenshot is from the file system of the server.
> Sadly, it's stored in 1080p rather than 4k on the server itself. So the quality is permanently lost. ![Image](https://github.com/user-attachments/assets/e823640a-f1c2-44b7-b26a-164a1c1b8b8d)

**Comment by Jogaxell** [comment]
Sadly, the issue is not fixed for me with.
I installed v6.1.7 from the Appstore.

Steps I took to reproduce the issue:
1. I took a 4k Video on my iPhone
2. I waited for the video to be uploaded to iCloud
3. I waited for my iPad to upload my new media from iCloud to my Nextcloud
4. Checking files

Original Video in iCloud 
![Image](https://github.com/user-attachments/assets/3a923294-6425-4145-aaa0-6737f5424671)
The corresponding file on my nextcloud
 ![Image](https://github.com/user-attachments/assets/67ca71b3-8a11-4333-adf3-ab3f73e7d57b)

**Comment by MrEcrm** [comment]
From my perspective the blame is on Apple.

I saved the very same file to the Apple Files app, resulting in the very same scenario: the file on the Photos app was considerably bigger than the file in the Files app. Actually, it had the same amount in the Files app as in Nextcloud. 

The solution:
1) settings, apps, Photos, (i have iCloud Photos turned off), Transferred to Mac or PC = keep originals
2) maybe reboot or any woodoo to make sure the changes take effect, might take some time?
3) open the video of photo you wanted to upload to Nextcloud, select it whatever
4) hit the share button, then first row it suggests some contacts to share (no!), next row airdrop, nextcloud app (nooo!!!), next row: gray (mimicking grayed out??) add to album, airplay, Export Unmodified Original (Yes!!)
5) Export Unmodified Original
6) navigate up (you might be in downloads folder …  —> “on my iphone”, Favorites (no!), below: Locations, find your nextcloud there* 
7) navigate through your folders until you land where to save it. 
8) save
9) open your nextcloud app
10) only now it uploads it in full quality and full size.
11) your players might have difficulty to play it because it might be heavy to process…

* requires to set up your nextcloud app with alternative username and app secret key/password more on  #3394 

To be all honest with you, I am extremely dissatisfied that Apple and others…  sell us best quality (photography) prices and then on every corner they try to reduce the quality of the images in their settings. They use by default not the highest and best quality settings. You need to manually adjust it to full quality. So far for camera settings.

When sending via WhatsApp or other messengers they only use mediocre quality by default (yes you believe sending good quality and get duped because it looks bad on the other end for the viewer!!).

When even sending to Nextcloud where you might have terabytes of free (redundant raid) space and you really don’t care about a few gigs more or less, they shrink and compress good quality to bad results! 

Selling honey and delivering sugar syrup, that’s what they do.
