### ISSUE TITLE
German

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#322]
![image1](https://user-images.githubusercontent.com/8616947/28709183-84ac0dae-737f-11e7-826f-b53285772498.PNG)

@rakekniven aa ss ? and where is the ampm ?  the point befor :  .... ?? Who translate ?

**Comment by yamlfd** [comment]
Since I reported this issue via email as I was not aware of this tracker. Thanks for posting it for me here.

German has no AM/PM!

Additionally to this the original string allowed me to have no dash between time and image number. If you customize the string the number of the photo is always prefixed with a dash. I think we also need a placeholder for the image number.

**Comment by yamlfd** [comment]
I just see that the sentence also has more German translation bugs.

Please change to:
> Beispielhafte Vorschau für den Dateinamen. Es kann das Schema MM, MMM,DD,YY,YYYY und HH,hh,mm,ss,am,pm für das Datum/die Zeit verwendet werden:

In German we typically add spaces after a comma like in English, too. I also flipped "das Datum/die Zeit" as you started above placeholders with a date and than time. So the order should be kept the same. Aside - a placeholder "am" and "pm" makes no sense as this is dynamic. I think this need to be ONE placeholder that returns am or pm. Looks like another bug.

**Comment by marinofaggiana** [comment]
@yamlfd no please modify, it's correct : 
 **ampm**

please see the English source for translate : 

https://www.transifex.com/nextcloud

**Comment by rakekniven** [comment]
Fixed it right now in Transifex. 
@yamlfd Danke für den Bericht.
