### ISSUE TITLE
Remove From Camera Roll After Successful Upload

### ISSUE THREAD

**Issue by cwmke** [nextcloud/ios#34]
Is it possible to remove the files from Camera Roll after they are successfully uploaded in nextcloud?

**Comment by marinofaggiana** [comment]
yes but the code will ask user to confirm removal from Camera Roll

https://developer.apple.com/reference/photos/phassetchangerequest/1624062-deleteassets

**Comment by cwmke** [comment]
One option would be to allow users to select an option to remove duplicates since it can't smoothly be automated. The option could be in the overflow menu.

**Comment by ClaudiuPID** [comment]
+ 1 for this feature.
Manually deleting images from mobile once in a while is not ideal.

**Comment by rEs-84** [comment]
+1 would much like for backed up pictures to be removed from the device. 
Especially if the photo viewer tab gets more usable. 

Can someone explain what "Remove files after upload" under advanced does, as it doesn't seem to remove anything.

**Comment by marinofaggiana** [comment]
@rEs-84 this option remove the file on cache locally after a upload

**Comment by rEs-84** [comment]
Interesting, makes sense (just doesn’t say cache).

Google photos has non automatic option to free up space by removing backed up photos.

**Comment by Happyfeet01** [comment]
Any news with this featurerequest?

**Comment by marinofaggiana** [comment]
@Happyfeet01 is too dangerous.

**Comment by army1349** [comment]
> 
> 
> @Happyfeet01 is too dangerous.

I think users should be able to decide what is too dangerous for them.

**Comment by Happyfeet01** [comment]
Why too dangerous

**Comment by HobbledGrubs** [comment]
I think it is maybe too dangerous at the moment.  My iOS app thinks that everything is uploaded but it has missed a lot of photos/movs.    There have been a number of bugs that (I use S3 type storage) that have prevented upload from completing correctly.  I have seen broken images on the Nextcloud side as well occasionally.  There is definitely a reliability problem at the moment.

**Comment by Happyfeet01** [comment]
Okay, that's too dangerous... what is your Workaround? My storage on the phone is full

**Comment by HobbledGrubs** [comment]
Not ideal.  I would generally check that the files were on Nextcloud via a browser and then delete.  I was on holiday two weeks ago and didn’t check because my connection was slow.  Bad mistake.  Although the app said everything had been uploaded, a few days of photos hadn’t and I deleted the movs thinking they had.   
It is currently stuck with about two months of photos not uploaded although it continues to upload new photos.   No workaround for that problem yet.

**Comment by Happyfeet01** [comment]
I try to delete the pictures and videos manually with PC Connection. And then every week. I would not use icloud photos

**Comment by HobbledGrubs** [comment]
Sounds tedious.  I think the feature would be good, iCloud photos manages the problem without trouble.  I imagine something like a hash/verify request to the server which can make sure the file exists on the Nextcloud server side.

**Comment by Happyfeet01** [comment]
Why tedious? I think about to use icloud Photos again. Until Nextcloud can solve this problem

**Comment by HobbledGrubs** [comment]
I meant doing it manually was tedious.   ICloud is great till you have to pay.  5Gig is peanuts today

**Comment by purefan** [comment]
@marinofaggiana The situation is that the space in Camera Roll runs out. 
We need to delete photos or videos to free up space. 
The NextCloud app can upload images and videos. 
After the photos/videos are uploaded to NextCloud we do not need them in the phone anymore. 
We can download them again from NextCloud if we want them. 
We are lazy and do not want to delete thousands of images by manually marking them one by one through the Camera Roll app, doing it this way is also risky because we are not sure which images/videos have been uploaded to NextCloud. But the NextCloud App does know this and has the power to delete these files from the phone.

Can you help us?

**Comment by apapenko** [comment]
@marinofaggiana why is this issue closed? Was it implemented?

**Comment by privettoli** [comment]
@marinofaggiana why is this issue closed? Was it implemented?

**Comment by marinofaggiana** [comment]
I have some ideas and I will do some tests ...

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/1240

**Comment by privettoli** [comment]
@marinofaggiana I think it's important to distinguish two scenarios here:
1. 
**GIVEN** an iOS user with a phone where storage is full of taken photos/videos
**WHEN** the user opens settings and click `Free Up Space` button
**THEN** all not uploaded photos and videos will be uploaded to NextCloud if there are any
**AND** my phone allows to confirm deletion of all already uploaded photos
**AND** my phone doesn't die due to low storage (should not download just uploaded files)

2.
**GIVEN** an iOS user with a phone where storage is not full 
**AND** the user sets auto-deletion of uploaded photos/videos after some period of time (let's say 1 month after they are taken) in settings
**WHEN** the photo/video was uploaded and was taken/shot before 1 month ago
**THEN** on next NC scan of files, those files are deleted
**AND** I see the notification with a list of files that were deleted

I see the first issue as critical because that's the situation a new NC faces when they have installed NC and want to free up space on their device.
The second issue can be considered as non-essential (nice to have) feature.

**Comment by clayrisser** [comment]
I'm still interested in this feature. It's what is holding me back from switching to nextcloud from Google photos.
