### ISSUE TITLE
folder name can be created with illegal characters

### ISSUE THREAD

**Issue by wizdude** [nextcloud/ios#345]
when creating a folder it is possible to use illegal characters such as < and >
this prevents the nextcloud desktop client from syncing the folder to other machines as these characters are not permitted on windows file systems.

for compatibility with windows machines you should not permit a file or folder to contain the characters:

\ / : * ? " < > |

cheers, wizdude

**Comment by marinofaggiana** [comment]
Yes, this is correct.

**Comment by rakekniven** [comment]
This should be blocked client side, or?

**Comment by rakekniven** [comment]
@marinofaggiana  How to proceed here?

**Comment by marinofaggiana** [comment]
Nothing i use the UNIX like permitted characters

**Comment by rakekniven** [comment]
This is a bug. Just created a file called "<>Unbenannt.txt" inside iOS app.

Windows desktop client says:
![grafik](https://user-images.githubusercontent.com/2069590/31457352-c8f667f2-aebc-11e7-8746-cda736457ace.png)

Windows is not unix :-)

**Comment by mcnesium** [comment]
Seems like this issue does still exist, could you please reopen @marinofaggiana? The latest iOS client is obviously able to create directories with illegal characters, but then fails to sync to a Nextcloud instance on a Linux machine with ext4 file system. No Windows involved.

More important though: how can this corrupt directory be deleted on the phone? Both deleting via the tripple dot menu and longtapping the folder and then selecting "delete" won't do anything, and the error message keeps popping up.

Background story: my parents just texted, sent a video (one phone filming the other) *and* called. They managed to create a folder with the name including a colon `:` in the iOS client. Suddenly half the screen is covered by a red and really alarming looking error message, that is literaly demanding to "solve the problem as soon as possible." Parents are freaking out, because they are unable to delete the corrupt directory, the error message keeps popping up every other second, they can no longer reach their holiday pictures, and I can not help right now because I live in a different city 😭 

Side note: I am not sure whether the alarming tone of that error message is really necessary.

**Comment by mcnesium** [comment]
> More important though: how can this corrupt directory be deleted on the phone? Both deleting via the tripple dot menu and longtapping the folder and then selecting "delete" won't do anything, and the error message keeps popping up.

fyi: removing the corrupt directory and thus the alarming error message can be done by logging out the user account from the app and then logging back in
