### ISSUE TITLE
Request: Cancel all pending Transfers

### ISSUE THREAD

**Issue by sunjam** [nextcloud/ios#425]
Please add the ability to cancel all pending Transfers.  I think of it as a "Force Kill" option.  Thanks!

**Comment by rakekniven** [comment]
You can stop each pending transfer seperatly. You like stop all of them with one action? "Killing" is a harsh word.

**Comment by sunjam** [comment]
Kill is an actual command, which dates back to old Unix systems.  _In computing, kill is a command that is used in several popular operating systems to send signals to running processes._. It would be nice to stop individual or all pending transfers completely.

**Comment by thisIsTheFoxe** [comment]
This is actually possible as of 2849bcca54c639e74100942c655041001189b64e. Tapping and holding the "stop" button on any upload it should display an alert asking if you want to cancel all. 
Although, there is an argument to be made in terms of UX. Personally, I think it might be more intuitive and discoverable to just have a navigation item "Cancel All" on top of the Transfers view. 

Closing this since the issue has been addressed. But feel free to give further feedback :)
