### ISSUE TITLE
Feature request: Healthkit integration

### ISSUE THREAD

**Issue by ladrua** [nextcloud/ios#639]
Wouldnt it be cool if we also synced the Health data somehow? Exporting the workouts as gpx files as one example.

**Comment by rakekniven** [comment]
@ladrua Have you seen other apps doing this besides Apple stuff? Do not know if this is possible...

**Comment by ladrua** [comment]
@rakekniven I havent seen sync of helath data. But I do have an app that manually exports my workouts to gpx files, and let me save them to files(hence my nextcloud folder) its called Porter(cant find a link attm). Also found this that looks interesting https://github.com/piscoTech/Workout . The Healthkit is pretty open, so I dont see why this should not be possible in one way or another, and health data I would say is(or will be) more valuble then my photos.

**Comment by ladrua** [comment]
Also found this https://www.fitnesssyncer.com/support/apple-healthkit that claim they do automatic background sync of Healthkit data to their platform.

**Comment by rakekniven** [comment]
Thank for doing a research.

Sounds interesting. Not sure if this should be part of an general nextcloud iOS app. Until now there is now functionality included besides core functions like sharing.

**Comment by MariusBluem** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by rakekniven** [comment]
Hello @MariusBluem Who is defining roadmap of iOS app? Marino and Frank? Or others? You can answer me via PM as well.

**Comment by MariusBluem** [comment]
Just a little workaround I have researched: https://www.macstories.net/ios/health-importer-makes-it-easy-to-move-health-data-between-iphones/ (Which is working with Nextcloud as storage)

@rakekniven 

> Who is defining roadmap of iOS app? Marino and Frank? Or others? 

The decision of the roadmap is made based on things Nextcloud Files and this iOS application "needs". 

The main focus is on file syncing & sharing and activities - respective for Nextcloud Talk and the Talk-app for iOS which is providing Chat+Calling-functionalities. We are working on bugfixes & features extending this application and user experience to an even higher level (for example **Document Scanner** https://github.com/nextcloud/ios/issues/644, **iOS Files-integration** https://github.com/nextcloud/ios/issues/268 - an request with 34x 👍 and 7x ❤ reactions on GitHub, just to be clear that we definitely listen to you). 

There is still a lot to do 🔧 ... Sometimes we need to prioritize things for enhancing the expected features instead of developing new/unstable/unsupported ones.

This HealthKit-stuff sounds very interesting - maybe you know somebody who wants to integrate that - we are definitely here for helping out. 👊 I am not really sure if this is possible in an iCloud/Apple-like way ... its the same for iCloud Backups (https://github.com/nextcloud/ios/issues/308) or things like Siri, HomeKit, Safari, Wallet, iMessage or Keychain via Nextcloud ... this app is not understanding itself as whole ecosystem replacement for the whole iCloud-functions. Even if we want that, we are limited here due to software restrictions. 

> You can answer me via PM as well.

Nothing to hide here 😅 What I've said above is a transparent workflow in the Nextcloud community. If you want to get in touch with me about this topic more detailed, feel free to send me an email to marius.bluem@nextcloud.com 😉 

cc @karlitschek

**Comment by adosix** [comment]
+1 

duno if it gets implemented some day but would be very nice.
