### ISSUE TITLE
Login from iOS via SAML iOS >= 11

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/ios#745]
From the iOS 11 the cookies lax from different domain are blocked.

I have found a workaround that resolve the issue but with a single domain creates a CSRF.

cc @MorrisJobke @Ivansss

**Comment by MorrisJobke** [comment]
> From the iOS 11 the cookies lax from different domain are blocked.

So the problem only exist for this scenario:

* having SSO via user_saml
* then the iOS app opens the login flow - lax cookies seem to be handled correctly
* login flow redirects to SSO IDP
* IDP redirects after authentication back to login flow
* expected: user is logged in to Nextcloud and redirect to nc://... happens
* actual: server misses the lax cookie and ends up in an endless loop to the same URL, because the cookie is not set (iOS seems to drop it)

@rullzer Any idea how to solve this? Should we maybe handle this a bit better on the server?

**Comment by mario** [comment]
@MorrisJobke according to my (fairly limited, and possibly wrong) the suggested solution would be to use SameSite=None instead of Lax anyway.

**Comment by marinofaggiana** [comment]
> would be to use SameSite=None instead of Lax anyway.

this should solve ....

**Comment by marinofaggiana** [comment]
cc @MorrisJobke @rullzer 

I make this issue in pause, this required an analysis server side ...

**Comment by williamsmt** [comment]
What was the outcome of this? I'm seeing exactly what @MorrisJobke identified as the 'actual', whereby the iOS app is in an endless loop to login.microsoftonline.com (the IdP) and never actually posts the token to NC. I attempted to add the user agent to csrf.optout thinking this would drop the cookie, but still seeing the same issue... Couldn't locate a corresponding issue # in the server project.

**Comment by rullzer** [comment]
@williamsmt there is a fix in server in the next maintenance release of nextcloud.

**Comment by williamsmt** [comment]
Fantastic @rullzer - do you have a commit id or issue number by chance? Will it be backported to NC14, or >= NC15?
