### ISSUE TITLE
Live Photo Support

### ISSUE THREAD

**Issue by moritz89** [nextcloud/ios#78]
I wanted to request support for live photos. This has been talked about a few times in the links below, but I haven't seen it as an active target recently. Would be interested to know how much effort it would be to implement this feature.

https://help.nextcloud.com/t/feature-request-support-ios-android-live-images-on-upload-and-galery/3632/8

https://github.com/owncloud/ios/issues/578

**Comment by jancborchardt** [comment]
Good call, do you know what needs to be changed in order to make this work?

cc @rwilliamsit since you seem to have made some research (see the original Oc issue)

**Comment by rwilliamsit** [comment]
Tumblr open source code for displaying live photos on the Web:  https://github.com/tumblr/laphs

Tumblr demo site: https://tumblr.github.io/laphs/

The above code serves a few purposes:
1. shows you how to display a live photo on the Web using javascript
2. Gives an idea of how live photos work

The above code does not:
1. show how to extract a live photo from an ios device (we need to figure this out ourselves)
2. Provide a method to scan/parse a library of live photos into a list. Not too hard to do, we already do this with normal photo libraries, but instead of one file live photos have two files and an attribute regarding timing (more on that later)
3. Provide a method or code that can show a live photo on something other than the Web, such as a native interface.

That being said, for each live photo we need to gather three main items:
1. the still jpg file
2. The mov file 
3. The time, in seconds, from the start of the video that the jpg represents (basically the number of seconds until the middle frame of the video)

Those three items are needed to properly catalog a library, display the still image, and play a live photo when clicked.

I am not a coder by profession... but reading the below API examples I am gathering that the general idea for us would be

1. use the general photo methods to list the photo library, use the live photo resource methods to download the data and write our own code to catalog it, and then upload the files and catalog to our own server that has the appropriate directory or file structure that can keep track of the live photo assets
2. Ensure the reverse is also possible: that we are organized enough and tracking the appropriate data whereas our live photos can be reimported into the iOS library 

This API reference talks about how to access live photo resources on an IOS device: 

iOS 9.1 introduces APIs that allow apps to incorporate playback of Live Photos, as well as export the data for sharing. 

The Photos framework includes support to fetch a PHLivePhoto object from the PHImageManagerobject, which is used to represent all the data that comprises a Live Photo. 

You can use a PHLivePhotoView object (defined in the PhotosUI framework) to display the contents of a Live Photo. The PHLivePhotoView view takes care of displaying the image, handling all user interaction, and applying the visual treatments to play back the content.

You can also use PHAssetResource to access the data of a PHLivePhoto object for sharing purposes. You can request a PHLivePhoto object for an asset in the user’s photo library by using PHImageManager or UIImagePickerController. If you have a sharing extension, you can also get PHLivePhotoobjects by using NSItemProvider. On the receiving side of a share, you can recreate a PHLivePhoto object from the set of files originally exported by the sender.

The data of a Live Photo is exported as a set of files in a PHAssetResource object. The set of files must be preserved as a unit when you upload them to a server. When you rebuild a PHLivePhoto with these files on the receiver side, the files are validated; loading fails if the files don’t come from the same asset.

**Comment by jancborchardt** [comment]
cc @marinofaggiana @nextcloud/ios since live photos are a pretty core feature of iOS now, we should support them of course. :)

**Comment by scar86** [comment]
Hi, not sure if this could help, but apple released and javascript api regarding Live Photos to show them on the web
https://developer.apple.com/live-photos/

**Comment by jancborchardt** [comment]
@scar86 oh, nice! Could you actually open an issue about that in our gallery app at https://github.com/nextcloud/gallery/issues :)

**Comment by baurmatt** [comment]
Would be awesome to have this feature. Any timeline for this?

**Comment by rakekniven** [comment]
For the records: https://github.com/nextcloud/gallery/issues/257

**Comment by jancborchardt** [comment]
@marinofaggiana any update here? :)

**Comment by derSoerrn95** [comment]
I'm interested in this feature, too. :-)

**Comment by maxxmka** [comment]
It’s basically just one more file to upload along with photo (short video file). But this should also support to upload these video files for the photos that has been already uploaded to cloud

**Comment by jancborchardt** [comment]
@marinofaggiana @nextcloud/ios as live photos are a pretty normal part of iOS now, it would be good to support this. :)

**Comment by marinofaggiana** [comment]
It’s in todo list but not for now...

**Comment by fefux** [comment]
Hello everybody. Just for information, @nextcloud/gallery team try to add live photos support into nextcloud release 14. See pull nextcloud/gallery#434

**Comment by MorrisJobke** [comment]
> It’s in todo list but not for now...

Any news?

Because this would be really nice. Also it's a data loss if the option "optimize space" is enabled, because only the photo is uploaded, but on deletion the only thing on your Nextcloud is the photo without the live part.

**Comment by maci2100** [comment]
Something new here?

**Comment by Griffun** [comment]
Is this still a planned feature?

**Comment by przerada** [comment]
Maybe after two years it is posible to upload .mov files needed for livephotos?
If we can upload it automaticly we can save our data

**Comment by marinofaggiana** [comment]
News: soon, after annual convention,  start the new look of internal viewer (live support included).

**Comment by toabctl** [comment]
@marinofaggiana, does that mean the mov files will be synced/uploaded automatically?that would be great

**Comment by logo000** [comment]
Any news about the ability to upload the full Live Photo?

**Comment by TheManchineel** [comment]
Bump. Any updates? Gallery is a great app and Live Photo support would make it the only selfhosted app supporting them.

**Comment by Petahh** [comment]
Before this is implemented, in iOS 13 you can go to albums, Live Photo’s, select all relevant pictures where you want video preserved and choose share, save as video. This will create export with videos to your camera roll which is then taken as regular video. I find this more convenient than actually. Choose only those which are important for you. 

+1 for the feature, if it will have reverse compatibility, meaning if picture is downloaded back to iOS from Nextcloud and iOS will be able to work with it as with Live Photo as before. Otherwise it will be just space blunder.

**Comment by ourcubk** [comment]
This is the most interesting feature for self host nas...
Please consider it into dev.

**Comment by stenioaraujo** [comment]
This feature would be great. I wish I knew how to help implementing it. In any case, Nextcloud is great.

**Comment by D-04** [comment]
Any news / plans on this?

**Comment by Floflobel** [comment]
I'm interested in this feature

**Comment by ownakasimon** [comment]
How many years are live photos now available on iOS? Please give some feedback :-( !

**Comment by marinofaggiana** [comment]
https://github.com/nextcloud/ios/issues/1187

**Comment by somsocorcim** [comment]
Hi guys,
Really great work. Any timeframe for the official release? This feature is the only missing one to set up the Nextcloud I have always dreamt of 😉

Regards,

somsocorcim
