### ISSUE TITLE
Background fetch instead of location update for pictures auto-transfer

### ISSUE THREAD

**Issue by immortal79** [nextcloud/ios#987]
Hello,

You are using location update for picture auto-transfer but this can lead to increased battery consomption and Apple could reject the app for not using CoreLocation for the right use case.

Did you consider using [background fetch api](https://developer.apple.com/documentation/uikit/app_and_environment/scenes/preparing_your_ui_to_run_in_the_background/updating_your_app_with_background_app_refresh) instead of using location update or is there a technical limitation that comes with using this API  ?

If you want I can start developing this feature.

**Comment by marinofaggiana** [comment]
Hi, we already use the fetch, look: 

https://github.com/nextcloud/ios/blob/9c0e102c2ae0d16c5ed5b8973c9406a0153e03de/iOSClient/AppDelegate.m#L1211

and do not exist a problem of reject with the location because the CoreLocation do not use the GPS signal (if not already present) but only the service already available as the triangulation of 3G/4G and do not use more battery.

Thanks
m.

**Comment by immortal79** [comment]
Ok, out of curiosity why are you using GPS instead of only relying on the background fetch ?

**Comment by marinofaggiana** [comment]
Because two is better than one :-) ... hahaha ... Fetch & CoreLocation are managed from O.S. and are triggered with a low priority. These are just a "work around" because is not possible work in background mode.

**Comment by immortal79** [comment]
Okay thank you for this explanation 👍
